
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:31 (project)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Linux - 6.13.7-gentoo-dist - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/arm-none-eabi-gcc 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3
      Id flags:  
      
      The output was:
      1
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x14): undefined reference to `_exit'
      /usr/libexec/gcc/arm-none-eabi/ld: (_exit): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-exit.o)
      exit.c:(.text.exit+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-closer.o): in function `_close_r':
      closer.c:(.text._close_r+0xc): undefined reference to `_close'
      /usr/libexec/gcc/arm-none-eabi/ld: (_close): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-closer.o)
      closer.c:(.text._close_r+0xc): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-lseekr.o): in function `_lseek_r':
      lseekr.c:(.text._lseek_r+0x14): undefined reference to `_lseek'
      /usr/libexec/gcc/arm-none-eabi/ld: (_lseek): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-lseekr.o)
      lseekr.c:(.text._lseek_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-readr.o): in function `_read_r':
      readr.c:(.text._read_r+0x14): undefined reference to `_read'
      /usr/libexec/gcc/arm-none-eabi/ld: (_read): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-readr.o)
      readr.c:(.text._read_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-writer.o): in function `_write_r':
      writer.c:(.text._write_r+0x14): undefined reference to `_write'
      /usr/libexec/gcc/arm-none-eabi/ld: (_write): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-writer.o)
      writer.c:(.text._write_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-sbrkr.o): in function `_sbrk_r':
      sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
      /usr/libexec/gcc/arm-none-eabi/ld: (_sbrk): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-sbrkr.o)
      sbrkr.c:(.text._sbrk_r+0xc): dangerous relocation: unsupported relocation
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/arm-none-eabi-gcc 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/fermata/Development/STM32/2023h_g474re/CMakeFiles/3.31.5/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/arm-none-eabi-g++ 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3;-fno-rtti;-fno-exceptions;-fno-threadsafe-statics
      Id flags:  
      
      The output was:
      1
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x14): undefined reference to `_exit'
      /usr/libexec/gcc/arm-none-eabi/ld: (_exit): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-exit.o)
      exit.c:(.text.exit+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-closer.o): in function `_close_r':
      closer.c:(.text._close_r+0xc): undefined reference to `_close'
      /usr/libexec/gcc/arm-none-eabi/ld: (_close): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-closer.o)
      closer.c:(.text._close_r+0xc): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-lseekr.o): in function `_lseek_r':
      lseekr.c:(.text._lseek_r+0x14): undefined reference to `_lseek'
      /usr/libexec/gcc/arm-none-eabi/ld: (_lseek): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-lseekr.o)
      lseekr.c:(.text._lseek_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-readr.o): in function `_read_r':
      readr.c:(.text._read_r+0x14): undefined reference to `_read'
      /usr/libexec/gcc/arm-none-eabi/ld: (_read): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-readr.o)
      readr.c:(.text._read_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-writer.o): in function `_write_r':
      writer.c:(.text._write_r+0x14): undefined reference to `_write'
      /usr/libexec/gcc/arm-none-eabi/ld: (_write): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-writer.o)
      writer.c:(.text._write_r+0x14): dangerous relocation: unsupported relocation
      /usr/libexec/gcc/arm-none-eabi/ld: /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-sbrkr.o): in function `_sbrk_r':
      sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
      /usr/libexec/gcc/arm-none-eabi/ld: (_sbrk): Unknown destination type (ARM/Thumb) in /usr/lib/gcc/arm-none-eabi/14/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libg.a(libc_a-sbrkr.o)
      sbrkr.c:(.text._sbrk_r+0xc): dangerous relocation: unsupported relocation
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/arm-none-eabi-g++ 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3;-fno-rtti;-fno-exceptions;-fno-threadsafe-statics
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/fermata/Development/STM32/2023h_g474re/CMakeFiles/3.31.5/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:35 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-none-eabi-gcc (Gentoo 14.2.1_p20241221 p7) 14.2.1 20241221
      Copyright (C) 2024 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
